/*
 * P2PTestFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package xwz.p2p.upd.server;

import java.net.SocketException;
import java.util.List;

import javax.swing.DefaultListModel;

import xwz.p2p.upd.util.ConnectionClientInfo;

/**
 *
 * @author  __USER__
 */
public class P2PSrvFrame extends javax.swing.JFrame {
	private static DefaultListModel dlmClientInfo = new DefaultListModel();
	private static List<ConnectionClientInfo> connClients = null;

	/** Creates new form P2PTestFrame */
	public P2PSrvFrame() {
		initComponents();

		getConnectionClientInfo();
		this.jList_onlineusrs.setModel(dlmClientInfo);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea_console = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jTextField_srvport = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jList_onlineusrs = new javax.swing.JList();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton_start = new javax.swing.JButton();
		jButton_end = new javax.swing.JButton();
		jButton_refresh = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("P2P Server");
		getContentPane().setLayout(null);

		jTextArea_console.setColumns(20);
		jTextArea_console.setRows(5);
		jScrollPane1.setViewportView(jTextArea_console);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(0, 170, 560, 170);

		jLabel2.setText("\u670d\u52a1\u5668UDP\u7aef\u53e3");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(10, 50, 110, 15);

		jTextField_srvport.setText("10000");
		getContentPane().add(jTextField_srvport);
		jTextField_srvport.setBounds(120, 50, 60, 21);

		jScrollPane2.setViewportView(jList_onlineusrs);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(70, 80, 380, 70);

		jLabel3.setText("\u5728\u7ebf\u7528\u6237");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(10, 80, 50, 20);

		jLabel4.setText("\u63a7\u5236\u53f0\u4fe1\u606f");
		getContentPane().add(jLabel4);
		jLabel4.setBounds(0, 150, 140, 15);

		jLabel5.setFont(new java.awt.Font("宋体", 1, 24));
		jLabel5.setText("P2P Server Test");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(20, 0, 330, 30);

		jButton_start.setText("\u542f\u52a8");
		jButton_start.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_startActionPerformed(evt);
			}
		});
		getContentPane().add(jButton_start);
		jButton_start.setBounds(190, 50, 70, 25);

		jButton_end.setText("\u505c\u6b62");
		jButton_end.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_endActionPerformed(evt);
			}
		});
		getContentPane().add(jButton_end);
		jButton_end.setBounds(260, 50, 70, 25);

		jButton_refresh.setText("\u5237\u65b0");
		jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_refreshActionPerformed(evt);
			}
		});
		getContentPane().add(jButton_refresh);
		jButton_refresh.setBounds(460, 80, 100, 70);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {
		getConnectionClientInfo();
	}

	public void getConnectionClientInfo() {
		dlmClientInfo.removeAllElements();
		
		connClients = MainServer.getConnectionClientInfo();
		for (ConnectionClientInfo clientInfo : connClients) {
			dlmClientInfo.addElement(clientInfo.getIp() + ':'+ clientInfo.getPort() + '/' + clientInfo.getNickname());
		}

	}

	private void jButton_endActionPerformed(java.awt.event.ActionEvent evt) {
		MainServer.stopP2PServer();
		dlmClientInfo.removeAllElements();

		String consoletxt = jTextArea_console.getText();
		consoletxt += "服务器已停止\r\n";
		jTextArea_console.setText(consoletxt);

		this.jButton_start.setEnabled(true);

	}

	private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {
		int port = Integer.parseInt(jTextField_srvport.getText());

		try {
			MainServer.startP2PServer(port);

			String consoletxt = jTextArea_console.getText();
			consoletxt += "服务器已启动\r\n";
			jTextArea_console.setText(consoletxt);
			this.jButton_start.setEnabled(false);

		} catch (SocketException e) {
			String consoletxt = jTextArea_console.getText();
			consoletxt += "启动服务器失败\r\n" + e.getMessage();
			jTextArea_console.setText(consoletxt);

		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton_end;
	private javax.swing.JButton jButton_refresh;
	private javax.swing.JButton jButton_start;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JList jList_onlineusrs;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea_console;
	private javax.swing.JTextField jTextField_srvport;
	// End of variables declaration//GEN-END:variables

}